"""empty message

Revision ID: 15544c98b49e
Revises: b63a8f2fef57
Create Date: 2023-01-25 13:42:35.823919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15544c98b49e'
down_revision = 'b63a8f2fef57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approver_request_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complainer_id', sa.Integer(), nullable=True),
    sa.Column('certificate', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='statusenum'), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['complainer_id'], ['complainer_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('complaint_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('photo_url', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='statusenum'), nullable=False),
    sa.Column('complainer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['complainer_id'], ['complainer_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.String(length=50), nullable=False),
    sa.Column('recipient_id', sa.String(length=20), nullable=False),
    sa.Column('target_account_id', sa.String(length=100), nullable=False),
    sa.Column('transfer_id', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('complaint_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaint_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_table')
    op.drop_table('complaint_table')
    op.drop_table('approver_request_table')
    # ### end Alembic commands ###
