"""Creaded new transaction table and added sort_code and account_number to complainer table

Revision ID: d6fa306949eb
Revises: f41b12facd87
Create Date: 2023-01-09 11:13:36.608279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6fa306949eb'
down_revision = 'f41b12facd87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.String(length=50), nullable=False),
    sa.Column('recipient_id', sa.String(length=20), nullable=False),
    sa.Column('transfer_id', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('complaint_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaint_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('complainer_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sort_code', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('account_number', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complainer_table', schema=None) as batch_op:
        batch_op.drop_column('account_number')
        batch_op.drop_column('sort_code')

    op.drop_table('transaction_table')
    # ### end Alembic commands ###
